import { test, expect } from '@playwright/test'

test('real demo completes adoption and care vertical slices', async ({ page }, testInfo) => {
  const pageErrors: string[] = []
  page.on('pageerror', error => pageErrors.push(error.message))
  // No route interception: every read/write goes through Vite to the real demo API.
  await page.goto('/')
  await page.getByRole('link', { name: 'Meet Mochi', exact: true }).click()
  const mochiUrl = page.url()
  const receipts: string[] = []
  for (const [name, email] of [['Freeze Alex', 'freeze-alex@example.com'], ['Freeze Sam', 'freeze-sam@example.com']]) {
    await page.getByLabel('Your name', { exact: true }).fill(name)
    await page.getByLabel('Email address', { exact: true }).fill(email)
    await page.getByRole('button', { name: 'Send adoption application', exact: true }).click()
    await expect(page).toHaveURL(/\/applications\/\d+$/)
    await expect(page.getByText('Pending review', { exact: true })).toBeVisible()
    receipts.push(page.url())
    if (receipts.length === 1) await page.goto(mochiUrl)
  }
  await page.getByRole('link', { name: 'Open demo staff review →', exact: true }).click()
  const winningApplication = page.locator('.application-item').filter({ hasText: 'freeze-alex@example.com' })
  await winningApplication.getByRole('button', { name: 'Approve', exact: true }).click()
  await winningApplication.getByRole('button', { name: 'Confirm decision', exact: true }).click()
  await expect(page.getByText('Application approved. The cat has found a home; other pending applications for this cat were declined.', { exact: true })).toBeVisible()
  await expect(page.locator('.application-item')).toHaveCount(0)
  await page.goto(receipts[0])
  await expect(page.locator('.receipt .status')).toHaveText('Approved')
  await page.goto(receipts[1])
  await expect(page.locator('.receipt .status')).toHaveText('Not approved')
  await page.goto(mochiUrl)
  await expect(page.getByText('A home has been found.', { exact: true })).toBeVisible()
  await page.goto('/')
  await page.getByRole('button', { name: 'Found a home', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Meet Mochi', exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'All cats', exact: true }).click()
  await page.getByRole('link', { name: 'Meet Nori', exact: true }).click()
  await expect(page.getByText('Our team is reviewing a care alert. Adoption is paused until the review is complete.', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Send adoption application', exact: true })).toHaveCount(0)
  await expect(page.getByText('40.00 °C', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Staff workspace', exact: true }).click()
  await page.getByRole('link', { name: 'Care alerts', exact: true }).click()
  const history = page.getByRole('list', { name: 'Health events, newest first' })
  await expect(page.getByRole('heading', { name: 'Nori', exact: true })).toBeVisible()
  await expect(history.getByText('OPEN', { exact: true })).toBeVisible()
  await expect(history.getByText('40.00 °C', { exact: true })).toBeVisible()
  await expect(history.getByText('38.30 °C', { exact: true })).toBeVisible()
  const before = await (await page.request.get('/api/alerts?status=OPEN')).json()
  const alert = before.find((item: { catName: string }) => item.catName === 'Nori')
  expect(alert).toBeDefined()

  await page.setViewportSize({ width: 390, height: 844 })
  const note = 'Freeze demo: temperature rechecked; fresh water offered; resting comfortably.'
  await page.getByLabel('Care note', { exact: false }).fill(note)
  await expect(page.getByRole('button', { name: 'Resolve care alert', exact: true })).toBeEnabled()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('care-open-narrow.png'), fullPage: true })
  await page.getByRole('button', { name: 'Resolve care alert', exact: true }).click()
  await expect(history.getByText('CLOSED', { exact: true })).toBeVisible()
  await expect(history.getByText(note, { exact: true })).toBeVisible()
  await expect(history.getByText(`Care action for alert #${alert.id}`, { exact: true })).toBeVisible()
  await expect(history.getByText('OPEN', { exact: true })).toHaveCount(0)
  await expect(page.getByText('No open care alerts.', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.setViewportSize({ width: 1440, height: 1100 })
  await page.screenshot({ path: testInfo.outputPath('care-closed-desktop.png'), fullPage: true })
  await page.getByRole('link', { name: 'View cat profile', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Send adoption application', exact: true })).toBeVisible()
  const dashboard = await (await page.request.get(`/api/cats/${alert.catId}/dashboard`)).json()
  expect(dashboard.status).toBe('NORMAL')
  expect(dashboard.hasActiveAlert).toBe(false)
  expect(pageErrors).toEqual([])
})
