import { test, expect } from '@playwright/test'

test('real demo completes adoption and care vertical slices', async ({ page }, testInfo) => {
  const pageErrors: string[] = []
  page.on('pageerror', error => pageErrors.push(error.message))
  // No route interception: every read/write goes through Vite to the real demo API.
  await page.goto('/')
  const initialCats = await (await page.request.get('/api/cats')).json()
  expect(initialCats).toHaveLength(6)
  const initialNori = initialCats.find((cat: { name: string }) => cat.name === 'Nori')
  expect(initialNori).toMatchObject({ adoptionStatus: 'AVAILABLE', healthStatus: 'UNDER_OBSERVATION' })
  expect(initialNori).not.toHaveProperty('status')
  await page.getByRole('link', { name: 'Meet Mochi', exact: true }).click()
  const mochiUrl = page.url()
  const receipts: string[] = []
  await expect(page.getByRole('link', { name: 'Sign in to apply', exact: true })).toBeVisible()
  await expect(page.getByLabel('Your name', { exact: true })).toHaveCount(0)
  for (const [email, password] of [['adopter@example.com', 'PawTrack-demo-adopter!'], ['other-adopter@example.com', 'PawTrack-demo-other!']]) {
    await page.getByRole('link', { name: 'Sign in to apply', exact: true }).click()
    await page.getByLabel('Email', { exact: true }).fill(email)
    await page.getByLabel('Password', { exact: true }).fill(password)
    await page.getByRole('button', { name: 'Sign in', exact: true }).click()
    await expect(page).toHaveURL(mochiUrl)
    await expect(page.locator('.applicant-identity')).toContainText(email)
    await expect(page.getByLabel('Email address', { exact: true })).toHaveCount(0)
    if (receipts.length === 0) await page.screenshot({ path: testInfo.outputPath('adopter-apply-desktop.png'), fullPage: true })
    await page.getByRole('button', { name: 'Send adoption application', exact: true }).click()
    await expect(page).toHaveURL(/\/applications\/\d+$/)
    await expect(page.getByText('Pending review', { exact: true })).toBeVisible()
    receipts.push(page.url())
    await page.getByRole('link', { name: 'My applications', exact: true }).first().click()
    await expect(page.getByRole('list', { name: 'My applications, newest first' }).getByRole('listitem')).toHaveCount(1)
    if (receipts.length === 2) {
      const forbidden = await page.request.get('/api/adoptions/' + receipts[0].split('/').pop())
      expect(forbidden.status()).toBe(404)
      expect(await forbidden.text()).not.toContain('adopter@example.com')
      await page.goto(receipts[0])
      await expect(page.getByRole('heading', { name: 'Application unavailable' })).toBeVisible()
      await expect(page.locator('.receipt')).toHaveCount(0)
    }
    await page.getByRole('button', { name: 'Sign out', exact: true }).click()
    await expect(page.getByRole('link', { name: 'Sign in', exact: true })).toBeVisible()
    expect((await page.request.get('/api/adoptions/' + receipts[0].split('/').pop())).status()).toBe(401)
    if (receipts.length === 1) await page.goto(mochiUrl)
  }
  await page.goto('/staff')
  await expect(page).toHaveURL(/\/login$/)
  expect((await page.request.get('/api/adoptions')).status()).toBe(401)
  await page.getByLabel('Email', { exact: true }).fill('staff@example.com')
  await page.getByLabel('Password', { exact: true }).fill('PawTrack-demo-staff!')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page).toHaveURL(/\/staff$/)
  const winningApplication = page.locator('.application-item').filter({ hasText: 'Demo Adopter' }).filter({ hasNotText: 'Other Demo Adopter' })
  await winningApplication.getByRole('button', { name: 'Approve', exact: true }).click()
  await winningApplication.getByRole('button', { name: 'Confirm decision', exact: true }).click()
  await expect(page.getByText('Application approved. The cat has found a home; other pending applications for this cat were declined.', { exact: true })).toBeVisible()
  await expect(page.locator('.application-item')).toHaveCount(0)
  await page.goto(receipts[0])
  await expect(page.locator('.receipt .status')).toHaveText('Approved')
  await page.goto(receipts[1])
  await expect(page.locator('.receipt .status')).toHaveText('Not approved')
  await page.goto(mochiUrl)
  await expect(page.getByText('A home has been found.', { exact: true })).toBeVisible()
  await page.goto('/')
  await page.getByRole('button', { name: 'Found a home', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Meet Mochi', exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'All cats', exact: true }).click()
  await page.getByRole('link', { name: 'Meet Nori', exact: true }).click()
  await expect(page.getByText('Our team is reviewing a care alert. Adoption is paused until the review is complete.', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Send adoption application', exact: true })).toHaveCount(0)
  await expect(page.getByText('40.00 °C', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Staff workspace', exact: true }).click()
  await page.getByRole('link', { name: 'Care alerts', exact: true }).click()
  const history = page.getByRole('list', { name: 'Health events, newest first' })
  await expect(page.getByRole('heading', { name: 'Nori', exact: true })).toBeVisible()
  await expect(history.getByText('OPEN', { exact: true })).toBeVisible()
  await expect(history.getByText('40.00 °C', { exact: true })).toBeVisible()
  await expect(history.getByText('38.30 °C', { exact: true })).toBeVisible()
  const before = await (await page.request.get('/api/alerts?status=OPEN')).json()
  const alert = before.find((item: { catName: string }) => item.catName === 'Nori')
  expect(alert).toBeDefined()

  await page.setViewportSize({ width: 390, height: 844 })
  const note = 'Freeze demo: temperature rechecked; fresh water offered; resting comfortably.'
  await page.getByLabel('Care note', { exact: false }).fill(note)
  await expect(page.getByRole('button', { name: 'Resolve care alert', exact: true })).toBeEnabled()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('care-open-narrow.png'), fullPage: true })
  await page.getByRole('button', { name: 'Resolve care alert', exact: true }).click()
  await expect(history.getByText('CLOSED', { exact: true })).toBeVisible()
  await expect(history.getByText(note, { exact: true })).toBeVisible()
  await expect(history.getByText(`Care action for alert #${alert.id}`, { exact: true })).toBeVisible()
  await expect(history.getByText('OPEN', { exact: true })).toHaveCount(0)
  await expect(page.getByText('No open care alerts.', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.setViewportSize({ width: 1440, height: 1100 })
  await page.screenshot({ path: testInfo.outputPath('care-closed-desktop.png'), fullPage: true })
  await page.getByRole('link', { name: 'View cat profile', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Adopter account required', exact: true })).toBeVisible()
  const dashboard = await (await page.request.get(`/api/cats/${alert.catId}/dashboard`)).json()
  expect(dashboard.healthStatus).toBe('NORMAL')
  expect(dashboard.adoptionStatus).toBe('AVAILABLE')
  expect(dashboard).not.toHaveProperty('status')
  expect(dashboard.hasActiveAlert).toBe(false)

  // Produce an independent health event through the existing observation API,
  // only in this runner's disposable H2 demo, after both original slices finish.
  const mochiId = new URL(mochiUrl).pathname.split('/').pop()
  const csrf = await (await page.request.get('/api/auth/csrf')).json()
  const fever = await page.request.post(`/api/cats/${mochiId}/health`, {
    data: { temperatureC: 40.00, activityLevel: 1 },
    headers: { [csrf.headerName]: csrf.token },
  })
  expect(fever.ok()).toBe(true)
  const adopted = await (await page.request.get(`/api/cats/${mochiId}/dashboard`)).json()
  expect(adopted.adoptionStatus).toBe('ADOPTED')
  expect(adopted.healthStatus).toBe('UNDER_OBSERVATION')
  expect(adopted.hasActiveAlert).toBe(true)
  expect(adopted).not.toHaveProperty('status')
  await page.goto(mochiUrl)
  await expect(page.getByText('Found a home', { exact: true })).toBeVisible()
  await expect(page.getByText('Under observation', { exact: true })).toBeVisible()
  await expect(page.getByText('A home has been found.', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Send adoption application', exact: true })).toHaveCount(0)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('adopted-under-observation-narrow.png'), fullPage: true })
  await page.goto('/')
  await page.getByRole('button', { name: 'Found a home', exact: true }).click()
  const mochiCard = page.getByRole('link', { name: 'Meet Mochi', exact: true })
  await expect(mochiCard.getByText('Found a home', { exact: true })).toBeVisible()
  await expect(mochiCard.getByText('Under observation', { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('adopted-under-observation-gallery.png'), fullPage: true })
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Sign in', exact: true })).toBeVisible()
  expect((await page.request.get('/api/adoptions')).status()).toBe(401)
  await page.goto('/staff/care')
  await expect(page).toHaveURL(/\/login$/)
  await page.screenshot({ path: testInfo.outputPath('staff-login-narrow.png'), fullPage: true })
  await page.getByLabel('Email', { exact: true }).fill('adopter@example.com')
  await page.getByLabel('Password', { exact: true }).fill('PawTrack-demo-adopter!')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Staff access required' })).toBeVisible()
  expect((await page.request.get('/api/adoptions')).status()).toBe(403)
  const adopterCsrf = await (await page.request.get('/api/auth/csrf')).json()
  expect((await page.request.patch(`/api/alerts/${alert.id}/resolve`, {
    headers: { [adopterCsrf.headerName]: adopterCsrf.token },
    data: { careType: 'CHECKUP', note: 'This ADOPTER write must be denied.' },
  })).status()).toBe(403)
  await page.getByRole('link', { name: 'Meet the cats', exact: true }).first().click()
  await expect(page.getByRole('link', { name: 'Meet Nori', exact: true })).toBeVisible()
  await page.goto(receipts[0])
  await expect(page.locator('.receipt .status')).toHaveText('Approved')
  await page.getByRole('link', { name: 'My applications', exact: true }).first().click()
  await expect(page.getByRole('list', { name: 'My applications, newest first' })).toContainText('Approved')
  await page.screenshot({ path: testInfo.outputPath('my-applications-narrow.png'), fullPage: true })
  expect(pageErrors).toEqual([])
})
