server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pawtrack
    username: pawtrack
    password: pawtrack
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

logging:
  level:
    org.hibernate.SQL: debug

upload:
  path: uploads/
